// Mapa de nombres de icono (string, definidos en siteConfig.js) a componentes lucide-react.
// Así el contenido puede editarse sin tocar los componentes ni las páginas.
import {
  Users,
  ShoppingBag,
  ChefHat,
  Sparkles,
  Store,
  Hotel,
  Building2,
  Truck,
  Package,
  Boxes,
  Rocket,
  ClipboardCheck,
  Calculator,
  BookOpenCheck,
  DoorOpen,
  GraduationCap,
  ShieldCheck,
  ClipboardList,
  LineChart,
  Wine,
  Cake,
  Briefcase,
  Search,
  UserRound,
  UtensilsCrossed,
  PartyPopper,
  Award,
  Flame,
  Home,
  Star,
  Factory,
  Utensils,
  HelpCircle,
} from 'lucide-react'

export const iconMap = {
  Users,
  ShoppingBag,
  ChefHat,
  Sparkles,
  Store,
  Hotel,
  Building2,
  Truck,
  Package,
  Boxes,
  Rocket,
  ClipboardCheck,
  Calculator,
  BookOpenCheck,
  DoorOpen,
  GraduationCap,
  ShieldCheck,
  ClipboardList,
  LineChart,
  Wine,
  Cake,
  Briefcase,
  Search,
  UserRound,
  UtensilsCrossed,
  PartyPopper,
  Award,
  Flame,
  Home,
  Star,
  Factory,
  Utensils,
}

export function getIcon(name) {
  return iconMap[name] || HelpCircle
}
